name: CD - Deploy Angular App to S3

on:
   push:
      branches: [main]

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         # 1. Checkout the main branch
         - name: Checkout code
           uses: actions/checkout@v4

         # 2. Set up Node.js
         - name: Use Node.js 22
           uses: actions/setup-node@v4
           with:
              node-version: 22
              cache: 'npm'

         # 3. Install dependencies
         - name: Install dependencies
           run: npm ci

         # 4. Build Angular app (production build)
         - name: Build Angular app
           run: npm run build

         # 5. Configure AWS credentials
         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v4
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

         # 6. Deploy to S3
         - name: Sync dist folder to S3
           run: |
              aws s3 sync dist/blog-frontend/browser s3://${{ secrets.AWS_S3_BUCKET }} \
                --delete
